[tool.poetry]
name = "tfonics"
version = "0.1.1"
description = "A collection of functions and utilities for the tfonics project"
authors = ["Ã˜yvind Almelid <oyvind.almelid@igmm.ed.ac.uk>"]
readme = "README.md"
repository = "https://git.ecdf.ed.ac.uk/oalmelid/tfonics"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
autopep8 = "^1.4"
pylint = "^2.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
